### ISSUE TITLE
Failures to get pars reference files in prefetch cause log messages

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5251]
_Issue [JP-1645](https://jira.stsci.edu/browse/JP-1645) was created on JIRA by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij):_

When step pars reference files are requested from CRDS when running a pipeline, log messages are printed if there is no such pars reference file found in CRDS.  Find a way to disable these messages, as there are many and they are distracting.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1645?focusedCommentId=488468#comment-488468):_

[PR #&#x2060;5375](https://github.com/spacetelescope/jwst/pull/5375) has been created. However, from discussions with the CRDS development team, another solution has presented itself. An email has been sent and reproduced below. Commentary welcome.

> Greetings,
> 
> 
> This note will describe a proposed change in how Step Parameter Reference Files
> are stored in CRDS. The changes are basically just organizational; there are no
> changes in implementation.
> 
> 
> Currently, step parameter reference files are located within the instruments'
> imaps and appear under the individual instrument listings. This placement has
> revealed a number of issues and potential issues:
> 
> 
> - There is a potential of having a significant number of step parameter reference types, crowding the reference listing for each instrument.
> - Difficulty in handling the sparsely populated domain space. There are and will always be a large number of steps and pipelines that will never have references defined. The main symptom of this is the unnecessary CRDS errors reported by the pipeline. With the current organization, changes would be required to core code to handle.
> - Difficult to determine coverage and difficult to discover what references could be created.
> - Conceptually, step parameter reference files are not instrument-specific, but observing-mode (exposure type) specific.
> 
> 
> To resolve these issues, the proposal is to create a new top-level imap,
> tentatively called "calpars", that would reside at the same level as the
> individual instruments. Conceptually, this category would contain all things
> that directly affect how the calibration pipeline runs. Advantages include:
> 
> - One stop listing of all potential and implemented step parameter reference types, without crowding the instrument-specific reference views.
> - As-designed handling of missing references without core code changes. No more spurious error messages.
> - Space for future expansion of similar references, such as association rules.
> 
> 
> The CRDS developers would like to hear thoughts and concerns about this proposal.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1645?focusedCommentId=496777#comment-496777):_

Issue resolved by CCD-783.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1645?focusedCommentId=488468#comment-488468):_

[PR #&#x2060;5375](https://github.com/spacetelescope/jwst/pull/5375) has been created. However, from discussions with the CRDS development team, another solution has presented itself. An email has been sent and reproduced below. Commentary welcome.

> Greetings,
> 
> 
> This note will describe a proposed change in how Step Parameter Reference Files
> are stored in CRDS. The changes are basically just organizational; there are no
> changes in implementation.
> 
> 
> Currently, step parameter reference files are located within the instruments'
> imaps and appear under the individual instrument listings. This placement has
> revealed a number of issues and potential issues:
> 
> 
> - There is a potential of having a significant number of step parameter reference types, crowding the reference listing for each instrument.
> - Difficulty in handling the sparsely populated domain space. There are and will always be a large number of steps and pipelines that will never have references defined. The main symptom of this is the unnecessary CRDS errors reported by the pipeline. With the current organization, changes would be required to core code to handle.
> - Difficult to determine coverage and difficult to discover what references could be created.
> - Conceptually, step parameter reference files are not instrument-specific, but observing-mode (exposure type) specific.
> 
> 
> To resolve these issues, the proposal is to create a new top-level imap,
> tentatively called "calpars", that would reside at the same level as the
> individual instruments. Conceptually, this category would contain all things
> that directly affect how the calibration pipeline runs. Advantages include:
> 
> - One stop listing of all potential and implemented step parameter reference types, without crowding the instrument-specific reference views.
> - As-designed handling of missing references without core code changes. No more spurious error messages.
> - Space for future expansion of similar references, such as association rules.
> 
> 
> The CRDS developers would like to hear thoughts and concerns about this proposal.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1645?focusedCommentId=496777#comment-496777):_

Issue resolved by CCD-783.

**Comment by jdavies-st** [comment]
This is still an issue, so I'm reopening.  For custom steps with reftypes listed and no parameter reference files in CRDS (they are custom steps), we still get this error message:

```
$ pip install snowblind
$ strun snowblind jw01335008001_02101_00001_nrs1_jump.fits
2024-01-18 12:29:58,676 - CRDS - ERROR -  Error determining best reference for 'pars-snowblindstep'  =   Unknown reference type 'pars-snowblindstep'
2024-01-18 12:29:58,677 - stpipe.SnowblindStep - INFO - SnowblindStep instance created.
2024-01-18 12:29:58,720 - stpipe.SnowblindStep - INFO - Step SnowblindStep running with args ('jw01335008001_02101_00001_nrs1_jump.fits',).
```

One could have `crds` continue to emit ERROR log message, or we could change these to INFO or WARNING.  Or we could just filter out the ERROR log messages in `stpipe`.  Thoughts?

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1645?focusedCommentId=950826#comment-950826):_

[Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) Would you consider lowering the log level of these messages from ERROR to INFO, or at least WARNING? 

Even for the cases where the step is part of the official pipeline, the lack of a pars- rmap does not kill the process, and so ERROR level doesn't seem warranted. It has caused repeated confusion in Operations when team members attempt to read the error logs. Most of these should now have been caught and empty rmaps added, but it's indicative of the issue James raises.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1645?focusedCommentId=951157#comment-951157):_

A check can be made for parameter files and simply produce an INFO message. Will create an issue momentarily and attach.
